name: ML Pipeline CI/CD

on:
  push:
    branches: [ main ]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install databricks-cli azureml-core opencv-python

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Configure Databricks CLI
      run: |
        mkdir -p ~/.databricks
        cat <<EOF > ~/.databricks/config
        [DEFAULT]
        host = ${{ secrets.DATABRICKS_HOST }}
        token = ${{ secrets.DATABRICKS_TOKEN }}
        EOF

    - name: Run and Wait for Databricks Job
      run: |
        RUN_ID=$(databricks jobs run-now --job-id ${{ secrets.DATABRICKS_JOB_ID }} --json | jq -r '.run_id')
        echo "Waiting for Databricks job (run_id=$RUN_ID) to complete..."

        while true; do
          STATUS=$(databricks runs get --run-id $RUN_ID --output)
          LIFE_CYCLE_STATE=$(echo $STATUS | jq -r '.state.life_cycle_state')
          RESULT_STATE=$(echo $STATUS | jq -r '.state.result_state')

          echo "Status: $LIFE_CYCLE_STATE, Result: $RESULT_STATE"

          if [[ "$LIFE_CYCLE_STATE" == "TERMINATED" ]]; then
            if [[ "$RESULT_STATE" == "SUCCESS" ]]; then
              echo "Databricks job completed successfully."
              break
            else
              echo "Databricks job failed with result: $RESULT_STATE"
              exit 1
            fi
          fi

          sleep 20
        done

    - name: Build and Push Docker Image
      run: |
        docker login testpractce123.azurecr.io -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
        docker build -t testpractce123.azurecr.io/diabetes-model:latest ./docker
        docker push testpractce123.azurecr.io/diabetes-model:latest

    - name: Deploy to AKS
      run: |
        az aks get-credentials --resource-group <your-resource-group> --name <your-aks-cluster>
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
